export { default as Widget } from './widget'
export { default as ImageWidget } from './imageWidget'
export { default as BackgroundWidget } from './backgroundWidget'
export { default as TextWidget } from './textWidget'
export { default as DrawRectWidget } from './drawRectWidget'
export { default as RectWidget } from './rectWidget'
export { default as CopiedWidget } from './copiedWidget'
